# Generated by Django 4.2.7 on 2023-12-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallchop', '0002_alter_event_time_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_type',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=200),
        ),
    ]
