# Generated by Django 4.2.7 on 2023-12-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallchop', '0010_remove_delivery_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smallchop.customer'),
        ),
    ]
