# Generated by Django 4.2.7 on 2023-12-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallchop', '0012_remove_shippingaddress_order_order_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
    ]
